spring:
  jpa:
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/template1
  properties:
    hibernate:
      dialect=org:
        hibernate:
          dialect:
            PostgreSQLDialect:
